### PR TITLE
feat: add color prop, don't add bg for non-raised button

### PR DESCRIPTION
**Pull request by satya164**
image

### CODE REVIEW

**Comment by satya164** [comment]
You can still add custom background color for non-raised buttons with`style` prop.

**Comment by ahmedlhanafy** [comment]
Looking good @satya164 will review once I get home

**Comment by ahmedlhanafy** [comment]
We will still need prop `fullWidth` I think

**Comment by satya164** [comment]
> We will still need prop fullWidth I think

If your parent view is `flexDirection: 'column'` and has `alignItems: 'stretch'` it will become full width (which is default). It's not full width in example because I'm using `flexDirection: 'row'`. Parent can use the style `alignItems: 'space-around'` or anything other than `stretch` to not have full-width buttons.

**Comment by ahmedlhanafy** [comment]
@satya164 I know that you didn't configure it and left it to the layout to be used, but I've seen this prop in different libraries makes it easier for beginners I guess

**Comment by satya164** [comment]
@ahmedlhanafy I think it's better for people to get familiar with flexbox rather than learning different props for each component. We can document this, but I'm against adding a prop.

**Comment by satya164** [comment]
ping @ahmedlhanafy

**Comment by ahmedlhanafy** [comment]
I will be on my computer on a while

**Comment by ahmedlhanafy** [comment]
@satya164 Great

**Pull request merged**
