### PR TITLE
docs: generate static html pages

### PR DESCRIPTION
**Pull request by satya164**
The development workflow is not very good right now since you need to rebuild after every change. Will need to revisit the approach.

Need to setup travis to build docs and push to the repo.

https://react-native-paper.github.io/

### CODE REVIEW

**Comment by ahmedlhanafy** [comment]
@satya164 Travis is failing

**Comment by ahmedlhanafy** [comment]
@satya164 checks are passing now should I review and merge now?

**Comment by satya164** [comment]
@ahmedlhanafy don't merge yet, I'm setting up automatic deployment for pages

**Comment by ahmedlhanafy** [comment]
@satya164 cool

**Pull request merged**
