### PR TITLE
Add Card.Cover, Card.Actions and Card.Content

### PR DESCRIPTION
**Pull request by satya164**
These components can adjust their styling automatically based on their siblings without any extra work on user's end. For example, the cover adjusts it's border radius, content adjusts it's padding, etc.

image

### CODE REVIEW

**Comment by ahmedlhanafy** [comment]
@satya164 I think that the space between the action buttons is big, it needs to be a little bit smaller

**Comment by ahmedlhanafy** [comment]
This is from MD docs @satya164 
screen shot 2016-11-20 at 2 44 40 pm

**Comment by satya164** [comment]
@ahmedlhanafy it looks like that cause there's horizontal margin of 8 and the guidelines say that button has to be at least 88dp wide. Not sure how to handle this. Probably can decrease horizontal margin. But that has to in `<Button />` so separate PR

**Comment by ahmedlhanafy** [comment]
8 in RN doesn't exactly translate to 8 dp @satya164

**Comment by satya164** [comment]
@ahmedlhanafy why not? it's device independent pixel

**Comment by ahmedlhanafy** [comment]
I have weird issues with it not exactly translating to what is shown in the MD docs

**Comment by satya164** [comment]
@ahmedlhanafy I guess we couldn't do much about it then. anyways, I'll decrease margin for button to 4 in another PR.

**Comment by ahmedlhanafy** [comment]
@satya164 perfect

**Comment by sanketsahusoft** [comment]
@satya164 @ahmedlhanafy This is coming out really great! 👍

**Pull request merged**
